name: arcore_example
description: A new project to learn how to use ARCore in your Flutter App

publish_to: "none"

version: 1.0.0+1
permission_handler: any

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts:
  ar_flutter_plugin: ^0.7.3
  qr_code_scanner: ^1.0.1
  convex_bottom_bar: ^3.2.0
  flutter_html: ^3.0.0-alpha.1
  shared_preferences: ^2.0.13
  video_player: ^2.6.1
  appinio_video_player: ^1.2.0
  audioplayers: ^3.0.1
  audio_video_progress_bar: ^1.0.1
  maps_launcher: ^2.2.0
  model_viewer_plus: ^1.5.0
  image_gallery_saver: ^1.7.1
  share_plus: ^6.3.4
  youtube_player_flutter: ^8.1.2
  flutter_cache_manager: ^3.3.0
  dio: ^4.0.0
  anim_search_bar: ^2.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/triangle.png
    - assets/Chicken_01/
    - assets/Dinasour/
    - assets/images/
